Employeelist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

employee/urls.py
from django.urls import path
from employee import views
app_name = 'App_Employee'

urlpatterns = [
    path('', views.Employees, name='employeelist'),
    path('login', views.LoginView, name="login"),
    path('signup', views.SignupView, name="signup"),
    path('logout', views.LogoutView, name="logout"),
    path('add', views.AddEmployee, name="addemployee"),
    path('details/<int:id>', views.SingleEmployee, name="details"),
    path('edit/<int:id>', views.EditEmployee, name="editemployee"),
    path('delete', views.DeleteEmployee, name="deleteemployee"),
]

employee/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class EmployeeList(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    FirstName=models.CharField(max_length=100,blank=False)
    LastName=models.CharField(max_length=100,blank=False)
    Email=models.CharField(max_length=100,blank=False)
    Phone=models.CharField(max_length=100,blank=False)
    Gender=models.CharField(max_length=100,blank=False)
    Age=models.CharField(max_length=100,blank=False)
    Dob=models.CharField(max_length=100,blank=False)
    City=models.CharField(max_length=100,blank=False)

    def __str__(self):
        return str(self.id)
    def get_fullname(self):
        return self.FirstName+" "+self.LastName

class Skill(models.Model):
    user=models.ForeignKey(EmployeeList,on_delete=models.CASCADE)
    skill=models.CharField(max_length=100,blank=False)

    def __str__(self):
        return str(self.user_id)

employee/views.py
from django.http import HttpRequest
from django.shortcuts import redirect, render
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import connection
from datetime import datetime
from employee.models import EmployeeList
from django.contrib.auth.decorators import login_required

@login_required(login_url='App_Employee:login')
def Employees(request):
    ps = 4
    pn = 1
    name=city=minage=maxage=gender=mindate=maxdate=""
    if request.method == "POST":
        name=request.POST.get('Formname',"")
        city=request.POST.get('FormCity',"")
        minage=request.POST.get('FormMinAge',"")
        maxage=request.POST.get('FormMaxAge',"")
        gender=request.POST.get('FormGender',"")
        mindate=request.POST.get('FormMinDate',"")
        maxdate=request.POST.get('FormMaxDate',"")
        
        qex = int(request.POST["PageNo"])
        if qex != "":
            pn = qex
    ExcludeRecors = (pn-1)*ps
    sql1="Select id,FirstName,LastName,Email,Gender,Phone,Dob,Age,City, count(1) over() TC From employee_employeelist "
    sql2=" user_id='"+str(request.user.id)+"' ORDER BY id DESC LIMIT " + str(ps) + " OFFSET "+str(ExcludeRecors)
    SqlQuery = ""
    if name!="":
        SqlQuery=SqlQuery + "( FirstName Like '%"+ name +"%' OR LastName Like '%"+name+"%' ) "
    if city!="" and city!="Select":
        if SqlQuery !="":
            SqlQuery=SqlQuery + " AND "
        SqlQuery=SqlQuery + " City='" + city + "'"
    if minage!="" and minage!="Min Age":
        if SqlQuery !="":
            SqlQuery=SqlQuery + " AND "
        SqlQuery=SqlQuery + "  Age>='" + minage + "' "    
    if maxage!="" and maxage!="Max Age":
        if SqlQuery !="":
            SqlQuery=SqlQuery + " AND "
        SqlQuery=SqlQuery + "  Age<='" + maxage + "' "    
    if mindate!="":
        if SqlQuery !="":
            SqlQuery=SqlQuery + " AND "
        SqlQuery=SqlQuery + "  Dob>='" + mindate + "' "  
    if maxdate!="":
        if SqlQuery !="":
            SqlQuery=SqlQuery + " AND "
        SqlQuery=SqlQuery + "  Dob<='" + maxdate + "' "  
    if gender!="":
        if SqlQuery !="":
            SqlQuery=SqlQuery+" AND "
        SqlQuery=SqlQuery + " Gender='" + gender + "'"
     

    if SqlQuery != "":
        SqlQuery =sql1+ " where "+SqlQuery+" AND "+sql2
    else:
        SqlQuery =sql1+ " where "+sql2
    print(SqlQuery)
    with connection.cursor() as cursor:
        cursor.execute(SqlQuery )
        all_employees = cursor.fetchall()
    PageCount = 0

    if len(all_employees) != 0:
        Totaldata = all_employees[0][9]
        ExtraPage = (Totaldata / ps)
        PageCount = round(Totaldata / ps)
        print(ExtraPage, PageCount)
        if ExtraPage > PageCount and PageCount >= 1:
            PageCount = PageCount+1
    print(PageCount)
    context = {
        'all_employees': all_employees,
        'pn': pn,
        'range': range(1, PageCount+1),
        'PageCount': PageCount,
        'name':name,
        'city':city,
        'minage':minage,
        'maxage':maxage,
        'mindate':mindate,
        'maxdate':maxdate,
        'minagerange':range(18,40),
        'maxagerange':range(30,80),
    }
    return render(request, 'employee/employee.html', context)


def LoginView(request):
    if request.user.is_authenticated:
        return redirect('App_Employee:employeelist')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('App_Employee:employeelist')
            else:
                messages.info(
                    request, "Enter correct username and password", extra_tags="login_error")
                return redirect('App_Employee:login')
    return render(request, 'employee/login.html')


def SignupView(request):
    if request.method == "POST":
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 != "" and password1 == password2:
            user = User.objects.create_user(
                username=username, password=password1)
            if user:
                messages.success(
                    request, "User Create Successfully", extra_tags="signup_complete")
            return redirect('App_Employee:signup')
    return render(request, 'employee/signup.html')


def LogoutView(request):
    logout(request)
    return redirect('App_Employee:login')


def calculateAge(birthDate):
    birthDate = datetime.strptime(birthDate, "%Y-%m-%d")
    days_in_year = 365.2425
    age = int((datetime.today() - birthDate).days / days_in_year)
    return age

@login_required(login_url='App_Employee:login')
def AddEmployee(request):

    if request.method == "POST":
        FormFirstName = request.POST.get("FormFirstName")
        FormLastName = request.POST.get("FormLastName", "")
        FormEmail = request.POST.get("FormEmail", "")
        FormPhone = request.POST.get("FormPhone", "")
        FormDob = request.POST["FormDob"]
        FormGender = request.POST.get("FormGender", "male")
        FormCity = request.POST.get("FormCity", "")
        FormAge = calculateAge(FormDob)
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO employee_employeelist (user_id,FirstName,LastName,Email,Gender,Phone,Dob,Age,City) VALUES('"+str(request.user.id) +
                           "','"+FormFirstName+"','"+FormLastName+"','"+FormEmail+"','"+FormGender+"','"+FormPhone+"','"+FormDob+"','"+str(FormAge)+"','"+FormCity+"')")
            newID = cursor.lastrowid

            ForkSkills = request.POST.getlist('Formskills')
            skillSql = "INSERT INTO  employee_skill (user_id,skill) VALUES "
            sql = ""
            for sk in ForkSkills:
                if sql != "":
                    sql = sql+","
                sql = sql+"( '"+str(newID)+"','"+sk+"') "
            finalskillSql = skillSql+sql
            cursor.execute(finalskillSql)
            cursor.close()
            messages.success(request, "Data Insert Successfully",
                             extra_tags="data_insert")
            return redirect('App_Employee:addemployee')

    return render(request, "employee/addemployee.html")

@login_required(login_url='App_Employee:login')
def SingleEmployee(request, id):
    with connection.cursor() as cursor:
        cursor.execute("SELECT E.id, E.FirstName ,E.LastName,E.Email,E.Phone,E.Gender,E.Age,E.Dob,E.City,S.skill,S.id, S.user_id FROM employee_employeelist E inner join employee_skill s on E.id = s.user_id Where E.id='"+str(id)+"'AND E.user_id='"+str(request.user.id)+"'")
        single_employee = cursor.fetchall()
    context = {
        'single_employee': single_employee,
    }
    return render(request, 'employee/singleemployee.html', context)

@login_required(login_url='App_Employee:login')
def EditEmployee(request,id):
    with connection.cursor() as cursor:
        cursor.execute("SELECT E.id, E.FirstName ,E.LastName,E.Email,E.Phone,E.Gender,E.Age,E.Dob,E.City,S.skill,S.id, S.user_id FROM employee_employeelist E inner join employee_skill s on E.id = s.user_id Where E.id='"+str(id)+"'AND E.user_id='"+str(request.user.id)+"'")
        single_employee = cursor.fetchall()
        cursor.close()
    print(single_employee)    
    if request.method=="POST":
        FormFirstName = request.POST.get("FormFirstName",single_employee[0][1])
        FormLastName = request.POST.get("FormLastName", single_employee[0][2])
        FormEmail = request.POST.get("FormEmail", single_employee[0][3])
        FormPhone = request.POST.get("FormPhone", single_employee[0][4])
        FormDob = request.POST["FormDob"]
        FormGender = request.POST.get("FormGender", single_employee[0][5])
        FormCity = request.POST.get("FormCity", single_employee[0][8])
        FormAge = calculateAge(FormDob)
        with connection.cursor() as cursor:
            cursor.execute("UPDATE employee_employeelist SET FirstName='"+FormFirstName+"',LastName='"+FormLastName+"',Email='"+FormEmail+"',Gender='"+FormGender+"',Phone='"+FormPhone+"',Dob='"+FormDob+"',Age='"+str(FormAge)+"',City='"+FormCity+"' WHERE id='"+str(id)+"' AND user_id='"+str(request.user.id)+"'")
            cursor.execute("Delete From employee_skill Where user_id='"+str(id)+"'")
            cursor.close()
        ForkSkills = request.POST.getlist('Formskills')
        skillSql = "INSERT INTO  employee_skill (user_id,skill) VALUES "
        sql = ""
        for sk in ForkSkills:
            if sql != "":
                sql = sql+","
            sql = sql+"( '"+str(id)+"','"+sk+"') "
        finalskillSql = skillSql+sql
        with connection.cursor() as cursor:
            cursor.execute(finalskillSql)
            cursor.close()
        messages.success(request, "Data Update Successfully",
                         extra_tags="data_update")
        return redirect('./%d'%id)
    context = {
        'single_employee': single_employee,
    }
    return render(request,"employee/editemployee.html",context)


def DeleteEmployee(request):
    
    if request.method=="POST":
        emp_id=request.POST["emp_id"]
        sql="SELECT E.id,E.user_id FROM employee_employeelist E inner join employee_skill s on E.id = s.user_id WHERE E.user_id ="+str(request.user.id)+" AND E.id ="+str(emp_id)
        with connection.cursor() as cursor:
            cursor.execute(sql)
            single_employee = cursor.fetchone()
            cursor.close()
        print(single_employee)  
        if len(single_employee)>0:
            with connection.cursor() as cursor:
                print("eid=",single_employee[0])

templates/employee/employee.html
{% extends 'base.html' %} 
{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}
{% block main %}
<section>
  <form id="filterForm" class="my-2" method="post">{% csrf_token %}
    {%for message in messages %} {%if "data_delete" in message.tags %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{message}} </strong>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endif %} {% endfor %} 
    <div class="bg-success py-2 rounded-top">
      <h4 class="text-white mx-2">Filter Zone</h4>
    </div>
    <div class="border border-success py-4">
      <div class="row px-4">
        <div class="col-md-4 my-2">
          <input
            type="text"
            class="form-control"
            placeholder="Search With Name"
            name="Formname"
            value="{{name}}"
          />
        </div>
        <div class="col-md-3 my-2">
          <select class="form-select" name="FormCity">
            {% if city != "" %}
            <option selected="" value="{{city}}">{{city}}</option>
            {% else %}
            <option selected=""> Select</option>
            {% endif %}
            <option value="Dhaka">Dhaka</option>
            <option value="Faridpur">Faridpur</option>
            <option value="Jamalpur">Jamalpur</option>
            <option value="Kishoreganj">Kishoreganj</option>
            <option value="Manikganj">Manikganj</option>
            <option value="Maradipur">Maradipur</option>
            <option value="Munshiganj">Munshiganj</option>
            <option value="Mymensingh">Mymensingh</option>
            <option value="Narayanganj">Narayanganj</option>
            <option value="Narsingdi">Narsingdi</option>
            <option value="Netrokona">Netrokona</option>
            <option value="Noakhali">Noakhali</option>
            <option value="Rajbari">Rajbari</option>
            <option value="Shariatpur">Shariatpur</option>
            <option value="Sherpur">Sherpur</option>
            <option value="Tangail">Tangail</option>
            <option value="Tongi">Tongi</option>
            <option value="Bagherhat">Bagherhat</option>
            <option value="Chuadanga">Chuadanga</option>
            <option value="Jessore">Jessore</option>
            <option value="Jhenaidaha">Jhenaidaha</option>
            <option value="Kushtia">Kushtia</option>
            <option value="Magura">Magura</option>
            <option value="Meherpur">Meherpur</option>
            <option value="Narail">Narail</option>
            <option value="Shatkhira">Shatkhira</option>
            <option value="Bogra">Bogra</option>
            <option value="Joypurhat">Joypurhat</option>
            <option value="Naogaon">Naogaon</option>
            <option value="Natore">Natore</option>
            <option value="Nawabganj">Nawabganj</option>
            <option value="Pabna">Pabna</option>
            <option value="Rajshahi">Rajshahi</option>
            <option value="Sirajganj">Sirajganj</option>
            <option value="Dinajpur">Dinajpur</option>
            <option value="Gaibandha">Gaibandha</option>
            <option value="Kurigram">Kurigram</option>
            <option value="Lalmonirhat">Lalmonirhat</option>
            <option value="Nilphamari">Nilphamari</option>
            <option value="Panchagarh">Panchagarh</option>
            <option value="Rangpur">Rangpur</option>
            <option value="Thakurgaon">Thakurgaon</option>
            <option value="Habiganj">Habiganj</option>
            <option value="Maulvibazar">Maulvibazar</option>
            <option value="Sunamganj">Sunamganj</option>
            <option value="Sylhet">Sylhet</option>
            <option value="Bandarban">Bandarban</option>
            <option value="Brahmanbaria">Brahmanbaria</option>
            <option value="Chandpur">Chandpur</option>
            <option value="Comilla">Comilla</option>
            <option value="Cox's Bazar">Cox's Bazar</option>
            <option value="Feni">Feni</option>
            <option value="Khagrachhari">Khagrachhari</option>
            <option value="Lakshmipur">Lakshmipur</option>
            <option value="Noakhali">Noakhali</option>
            <option value="Rangamati">Rangamati</option>
            <option value="Barguna">Barguna</option>
            <option value="Barisal">Barisal</option>
            <option value="Bhola">Bhola</option>
            <option value="Jhalokati">Jhalokati</option>
            <option value="Patuakhali">Patuakhali</option>
            <option value="Pirojpur">Pirojpur</option>
          </select>
        </div>
        <div class="col-md-2 my-2">
          <select class="form-select" name="FormMinAge">
            {% if minage != "" %}
            <option selected="" value="{{minage}}">{{minage}}</option>
            {% else %}
            <option selected>Min Age</option>
            {% endif %}
            {% for ma in minagerange%}
            <option value="{{ma}}">{{ma}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col-md-2 my-2">
          <select class="form-select" name="FormMaxAge">
             {% if maxage != "" %}
            <option selected="" value="{{maxage}}">{{maxage}}</option>
            {% else %}
            <option selected>Max Age</option>
            {% endif %}
            {% for ma in maxagerange%}
            <option value="{{ma}}">{{ma}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col-md-2 my-2">
          <input
            type="date"
            class="form-control"
            name="FormMinDate"
            value="{{mindate}}"
          />
          
        </div>
         <div class="col-md-2 my-2">
          <input
            type="date"
            class="form-control"
            name="FormMaxDate"
            value="{{maxdate}}"
          />
          
        </div>
        <div class="col-md-4">
          <div class="my-3"></div>
          <div class="radio-inline mr-2">
              <input type="radio" value="male" name="FormGender">&nbsp;Male
          </label>
          <label class="radio-inline mx-2">
            <input type="radio" value="female" name="FormGender">&nbsp;Female
          </label>
          </div>
      </div>
        <div class="col-md-12">
          <input type="hidden" name="PageNo" id="PageNo" value="{{pn}}"/>
            <button id="filterBtn" type="submit" class="btn btn-primary btn-sm my-2">Filter</buton>
        </div>
      </div>
    </div>
  </form>
</section>
<section>
  <div class="row">
    <div class="col">
      <a class="btn btn-success" href="{% url 'App_Employee:addemployee'%}">Add New</a>
    </div>
    <div class="col">
      <nav>
       <ul class="pagination">
        {% if pn > 1 %}
            <li class="page-item"><a class="page-link" onclick="ChangePageNoValue({{pn|add:"-1"}})" >Previous</a></li>
        {% endif %}
        
        {%  for i in range  %}
            {% if i == pn %}
                <li class="page-item active"><a class="page-link"  onclick="ChangePageNoValue({{i}})">{{i}}</a></li>
            {% else %}
                <li class="page-item "><a class="page-link"  onclick="ChangePageNoValue({{i}})">{{i}}</a></li>
            {% endif%}
        {%  endfor %}
        
        {% if pn < PageCount %}
            <li class="page-item"><a class="page-link"  onclick="ChangePageNoValue({{pn|add:"1"}})">Next</a></li>
        {% endif %}
        
    </ul>
      </nav>
    </div>
  </div>  


</section>
<section>
  <div class="table-responsive">
  <table class="table table-striped table-hover">
    <h6>Total {{all_employees.0.9}}</h6>
    <thead>
      <tr>
        <th scope="col">SL</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Gender</th>
        <th scope="col">Phone</th>
        <th scope="col">Dob</th>
        <th scope="col">Age</th>
        <th scope="col">City</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for emp in all_employees %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{emp.1}} {{emp.2}}</td>
        <td>{{emp.3}}</td>
        <td>{{emp.4}}</td>
        <td>{{emp.5}}</td>
        <td>{{emp.6}}</td>
        <td>{{emp.7}}</td>
        <td>{{emp.8}}</td>
        <td>
          <a href="{% url 'App_Employee:details' emp.0%}">View</a> ||
          <a href="{% url 'App_Employee:editemployee' emp.0 %}">Edit</a> ||
          <a href="" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="changemodalvalue({{emp.0}})">Delete </a>
        </td>
      </tr>
      {% endfor %}
     
    </tbody>
  </table>
</div>
</section>
<script>
var pageno=document.getElementById("PageNo")
  function ChangePageNoValue(val){
    pageno.value=val;
    filterbuttonAction();
  }
  document.getElementById("filterBtn").addEventListener("click", filterbuttonAction);
  function filterbuttonAction() {
    document.getElementById("filterForm").submit();
  };
  function changemodalvalue(val){
    var x=document.getElementById("emp_id");
    x.value=val;
  }
</script>  
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      Are you want to delete this Employee?
      </div>
      <form method="post" action="{% url 'App_Employee:deleteemployee'%}">{% csrf_token %}
      <div class="modal-footer">
        <input type="hidden" name="emp_id" id="emp_id" value=""/>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" id="deleteBtn" class="btn btn-primary">Delete</button>
      </div>
      </form>
    </div>
  </div>
</div>
{% endblock main %}

templates/employee/login.html
{% extends 'base.html' %} {% block main %}
<section>
  <form method="post" action="{% url 'App_Employee:login'%}">
    {% csrf_token %}
    <div class="loginForm">
      {%for message in messages %} {%if "login_error" in message.tags %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{message}} </strong>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endif %} {% endfor %}
      <div class="card shadow-lg p-4">
        <h3 class="login-title">Login Form</h3>
        <div class="form-floating mb-3">
          <input
            type="text"
            class="form-control"
            id="floatingInput"
            name="username"
            placeholder="Username"
          />
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          <input
            type="password"
            class="form-control"
            id="floatingPassword"
            name="password"
            placeholder="Password"
          />
          <label for="floatingPassword">Password</label>
        </div>
        <div class="my-2">
          <a class="text-danger" href="{% url 'App_Employee:signup'%}"
            >Signup Now</a
          >
        </div>
        <div class="my-2">
          <button type="submit" class="btn btn-primary">Login</button>
        </div>
      </div>
    </div>
  </form>
</section>
{% endblock main %}

templates/employee/signup.html
{% extends 'base.html' %} {% block main %}
<section>
  <form method="post" actions="{% url 'App_Employee:signup'%}">
    {% csrf_token %}
    <div class="signupForm">
      {%for message in messages %} {%if "signup_complete" in message.tags %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{message}} </strong>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endif %} {% endfor %}
      <div class="card shadow-lg p-4">
        <h3 class="login-title">Signup Form</h3>
        <div class="form-floating mb-3">
          <input
            type="text"
            class="form-control"
            id="floatingInput"
            placeholder="Enter username"
            name="username"
            required
          />
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          <input
            type="password"
            class="form-control"
            id="floatingPassword"
            name="password1"
            placeholder="Password"
            required
          />
          <label for="floatingPassword">Password</label>
        </div>
        <div class="form-floating my-2">
          <input
            type="password"
            class="form-control"
            id="floatingPassword"
            name="password2"
            placeholder="Password"
            required
          />
          <label for="floatingPassword">Confirm Password</label>
        </div>

        <div class="my-2">
          <a class="text-danger" href="{% url 'App_Employee:login'%}"
            >Login Now</a
          >
        </div>
        <div class="my-2">
          <button type="submit" class="btn btn-primary">Login</button>
        </div>
      </div>
    </div>
  </form>
</section>
{% endblock main %}

templates/employee/singleemployee.html
{% extends 'base.html' %} {% block title%} Signle Employee {% endblock title%}
{% block navbar%}{% include 'navbar.html'%}{% endblock navbar%} {% block main %}

<section>
  <div>
    <div>
      <h4>Employee Details Page</h4>
    </div>
    <div>
      <table class="table table-bordered w-50">
        <tr>
          <td>Full Name</td>
          <td>{{single_employee.0.1}} {{single_employee.0.2}}</td>
        </tr>
        <tr>
          <td>Email</td>
          <td>{{single_employee.0.3}}</td>
        </tr>
        <tr>
          <td>Phone</td>
          <td>{{single_employee.0.4}}</td>
        </tr>
        <tr>
          <td>Gender</td>
          <td>{{single_employee.0.5}}</td>
        </tr>
        <tr>
          <td>Dath of Birth</td>
          <td>{{single_employee.0.7}}</td>
        </tr>
        <tr>
          <td>Age</td>
          <td>{{single_employee.0.6}}</td>
        </tr>
        <tr>
          <td>City</td>
          <td>{{single_employee.0.8}}</td>
        </tr>
        <tr>
          <td>Skills</td>
          <td>
            <ul>
              {% for s in single_employee %}
                  <li>{{s.9}}</li>
              {% endfor %}
            </ul>
          </td>
        </tr>
      </table>
    </div>
  </div>
</section>

{% endblock main %}