Employeelist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

employee/urls.py
from django.urls import path
from employee import views
app_name = 'App_Employee'

urlpatterns = [
    path('', views.Employees, name='employeelist'),
    path('login', views.LoginView, name="login"),
    path('signup', views.SignupView, name="signup"),
    path('logout', views.LogoutView, name="logout"),
    path('add', views.AddEmployee, name="addemployee"),
    path('details/<int:id>', views.SingleEmployee, name="details"),
    path('edit/<int:id>', views.EditEmployee, name="editemployee"),
    path('delete', views.DeleteEmployee, name="deleteemployee"),
]

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Home Page{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" />
    <link href="{% static 'css/style.css'%}" rel="stylesheet" />
  </head>
  <body>
    {% block navbar%}{% endblock navbar%}
    <div class="container">{% block main %} {% endblock main %}</div>

    <script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/validation.js'%}"></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'App_Employee:employeelist'%}"
      >JS ERP</a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'App_Employee:employeelist'%}"
            >EmployeList</a
          >
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Employee:logout'%}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Welcome {{request.user}} </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a
            class="nav-link"
            aria-current="page"
            href="{% url 'App_Employee:login'%}"
            >Login</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Employee:signup'%}">SignUp</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>